language: python

sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=ESP32LapTimer
install:
    - pip install -U platformio
    - pio update
    # This is a dirty hack to make our custom partition table work with the ci command
    - cp ESP32LapTimer/timer_partitions.csv ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/timer_partitions.csv
script:
    - pio ci --project-conf=ESP32LapTimer/platformio.ini
    - ls *
    - pwd
