language: python

sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=ESP32LapTimer
install:
    - pip install -U platformio
    - pio update
script:
    - pio ci --project-conf=ESP32LapTimer/platformio.ini
    - ls *
    - pwd
